/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_smarteair_net_NetWorkManager */

#ifndef _Included_com_example_smarteair_net_NetWorkManager
#define _Included_com_example_smarteair_net_NetWorkManager
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_example_smarteair_net_NetWorkManager
 * Method:    start
 * Signature: ()V
 */



JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_JniNetWorkInit
  (JNIEnv *env, jobject jo,  jint sn, jint group_id, jbyteArray check);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_NetWorkExit
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_NetWorkPause
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_NetWorkResume
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_EntryScanMode
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_ExitScanMode
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_AddDevie
(JNIEnv *env, jobject jo, jint sn);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_DelDevie
(JNIEnv *env, jobject jo, jint sn);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_ActiveDevice
(JNIEnv *env, jobject jo, jint sn);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_DisActiveDevice
(JNIEnv *env, jobject jo, jint sn);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_DisActiveAll
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_GetDeviceLinkStatus
(JNIEnv *env, jobject jo, jint sn);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_GetServiceLinkStatus
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_JniApConfig
    (JNIEnv *env, jobject jo, jbyteArray ssid, jbyteArray password,  jint add_wifi);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_CancelAPConfig
(JNIEnv *env, jobject jo);

JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_SendData
(JNIEnv *env, jobject jo, jint sn, jint datalen, jbyteArray data);


JNIEXPORT int JNICALL Java_com_example_smarteair_net_NetWorkManager_registerUserInfo
(JNIEnv *env, jobject jo, jstring user_sn, jstring name, jstring phone, jstring province, jstring city, jstring district, jstring other);


#ifdef __cplusplus
}
#endif
#endif
